import moment from "moment";

const _actionItems = [
  {
    id: 1,
    title: "Trial to confirm/test variable correlations",
    assignee: "John Doe",
    status: "To Start",
    correspondingOpportunity: "Reduce Heat-up Sub-Phase 2 Variation",
    dueDate: moment().add(1, "days").format("Do MMM Y"),
  },
  {
    id: 2,
    title: "Trial ∆T programming on individual batches",
    assignee: "Jane Doe",
    status: "In Progress",
    correspondingOpportunity: "Quick cool vessel",
    dueDate: moment().add(4, "days").format("Do MMM Y"),
  },
  {
    id: 3,
    title: "Trial ∆T programming on campaign ",
    assignee: "Sebastian Cricket",
    status: "On Hold",
    correspondingOpportunity: "Raise cooldown set-point",
    dueDate: moment().add(6, "days").format("Do MMM Y"),
  },
  {
    id: 4,
    title: "Trial increased cooldown set-point",
    assignee: "Sebastian Cricket",
    status: "To Start",
    correspondingOpportunity: "Adjust Cool profile to max heat transfer",
    dueDate: moment().add(10, "days").format("Do MMM Y"),
  },
  {
    id: 5,
    title: "Compare trial phase batches to previous 10%ile batches",
    assignee: "John Doe",
    status: "To Start",
    correspondingOpportunity: "Increase transfer temps",
    dueDate: moment().add(1, "days").format("Do MMM Y"),
  },
  {
    id: 6,
    title: "Change hard-wired set-point on asset",
    assignee: "Jane Doe",
    status: "Completed",
    correspondingOpportunity: "Increase Heat Up Speed",
    dueDate: moment().add(3, "days").format("Do MMM Y"),
  },
  {
    id: 7,
    title: "Understand re-boiler constraint",
    assignee: "Sebastian Cricket",
    status: "Completed",
    correspondingOpportunity: "Reduce circulation time",
    dueDate: moment().add(2, "days").format("Do MMM Y"),
  },
  {
    id: 8,
    title: "Work order for re-ranging pressure transmitters",
    assignee: "John Doe",
    status: "On Hold",
    correspondingOpportunity: "Update Drying Steps",
    dueDate: moment().format("Do MMM Y"),
  },
  {
    id: 9,
    title: "Update acetylator heat up programming ",
    assignee: "Sebastian Cricket",
    status: "On Hold",
    correspondingOpportunity: "Update Drying Steps",
    dueDate: moment().add(11, "days").format("Do MMM Y"),
  },
  {
    id: 10,
    title: "Conduct pressure test",
    assignee: "Sebastian Cricket",
    status: "To Start",
    correspondingOpportunity: "Startup Automation",
    dueDate: moment().add(14, "days").format("Do MMM Y"),
  },
];

export default _actionItems;
